# This is a basic workflow to help you get started with Actions

name: Testing the translated Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Add more: de_DE, ja_JP, es_ES, es_MX, fr_FR, it_IT, ko_KR, pt_BR, pt_PT, tr_TR
        language: [de_DE]
#   if: "contains(github.event.head_commit.message, 'New translations ')"

    steps:
    - uses: actions/checkout@v2

    - name: get labels name
#       if: contains(github.event.label.name, 'gh-pages')
      run: |
         echo ${{ github.event.head_commit }}
         echo "test me"
          
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.8'
        
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -U virtualenv setuptools wheel
#         pip install -U -r requirements-dev.txt sphinx-intl qiskit
#         sudo apt-get install graphviz pandoc
        
#     - name: Build translated Qiskit Docs
#       env:
#         TRANSLATION_LANG: ${{ matrix.language }}
#         REPO_TOKEN: ${{ secrets.STAGING_KEY }}
#       run: |
#         tools/production_translated_documentation.sh
        
#     - name: Install SSH Client
#       uses: webfactory/ssh-agent@v0.2.0
#       with:
#           ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    
#     - name: Deploy to gh-pages
#       uses: JamesIves/github-pages-deploy-action@3.5.6
#       with:
#         BASE_BRANCH: master
#         BRANCH: gh-pages
#         FOLDER: build
#         CLEAN_EXCLUDE: '["README.md"]'
#         SSH: true # SSH must be set to true so the deploy action knows which protocol to deploy with.
      
